# Generated by Django 2.1.5 on 2019-02-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(max_length=260)),
                ('position', models.IntegerField()),
                ('url', models.CharField(max_length=50)),
                ('marker', models.CharField(max_length=260)),
                ('routeMarker', models.CharField(max_length=260)),
                ('routeColor', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('location', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=260, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Inside',
            fields=[
                ('room', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('building', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inside',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('moreInfo', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
