# Generated by Django 2.1.5 on 2019-04-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subareas', serialize=False, to='api.Location')),
            ],
            options={
                'db_table': 'subarea',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='moreinfo',
        ),
        migrations.AddField(
            model_name='location',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
