# Generated by Django 2.1.5 on 2019-04-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inside',
        ),
    ]
