# Generated by Django 2.1.5 on 2019-04-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inside_clear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
