# Generated by Django 2.1.5 on 2019-04-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove-admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.ManyToManyField(related_name='tags', to='api.Location')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.AlterModelOptions(
            name='subarea',
            options={},
        ),
    ]
