# Generated by Django 2.1.5 on 2019-04-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarea',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='api.Location'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='sub',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='building', serialize=False, to='api.Location'),
        ),
    ]
